run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - exhaustive
    - wrapcheck

linters-settings:
  errcheck:
    # Ignore errors from these functions (commonly safe to ignore)
    exclude-functions:
      - (github.com/pterm/pterm.SpinnerPrinter).Start
      - (github.com/pterm/pterm.SpinnerPrinter).Stop
      - (github.com/pterm/pterm.SpinnerPrinter).Success
      - (github.com/pterm/pterm.SpinnerPrinter).Fail
      - (*github.com/pterm/pterm.InteractiveConfirmPrinter).Show
      - (*github.com/pterm/pterm.InteractiveSelectPrinter).Show
      - (github.com/pterm/pterm.TablePrinter).Render
      - (*github.com/spf13/pflag.FlagSet).GetString
      - (*github.com/spf13/pflag.FlagSet).GetBool

issues:
  exclude-rules:
    # Ignore error returns from pterm display functions
    - path: cmd/
      linters:
        - errcheck
      text: "Error return value of .*(pterm|Render|Print)"

