project_name: lockr

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    binary: lockr

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: devops-chris
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/devops-chris/lockr"
    description: "A simple CLI for managing secrets in AWS SSM Parameter Store"
    license: "MIT"
    # Skip Homebrew for pre-releases (alpha, beta, rc)
    skip_upload: auto
    install: |
      bin.install "lockr"
    test: |
      system "#{bin}/lockr", "version"

release:
  github:
    owner: devops-chris
    name: lockr
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

